### ISSUE TITLE
Hoshi set text programmatically after it's drawn

### ISSUE THREAD

**Issue by LadyRanger1992** [raulriera/TextFieldEffects#33] opened 2015-09-30 04:34 UTC
hello, Raul.
The issue same with https://github.com/raulriera/TextFieldEffects/issues/13 still visible in my app.
I using your library in Objective-C project, when I set text are emty string, the placeholder string do not move down.
```javascript
Objective-C
_nameText = [[HoshiTextField alloc] initWithFrame:CGRectMake(xPos, yPos, WIDTH - 10, WIDTH0.1667)];
[_nameText setBorderActiveColor:[UIColor LVL_colorWithHexString:@"ffc16a" andAlpha:1.0]];
[_nameText setBorderInactiveColor:[UIColor LVL_colorWithHexString:@"d0d0d0" andAlpha:1.0]];
[_nameText setPlaceholder:@" Name:"];
[self.pageScroll addSubview:_nameText];
yPos += WIDTH0.1667 + 5;

_title = [[HoshiTextField alloc] initWithFrame:CGRectMake(xPos, yPos, WIDTH - 10, WIDTH*0.1667)];
[_title setBorderActiveColor:[UIColor LVL_colorWithHexString:@"ffc16a" andAlpha:1.0]];
[_title setBorderInactiveColor:[UIColor LVL_colorWithHexString:@"d0d0d0" andAlpha:1.0]];
[_title setPlaceholder:@"  Title:"];
[self.pageScroll addSubview:_title];
yPos += WIDTH*0.1667 + 5;

_comment = [[HoshiTextField alloc] initWithFrame:CGRectMake(xPos, yPos, WIDTH - 10, WIDTH*0.1667)];
[_comment setBorderActiveColor:[UIColor LVL_colorWithHexString:@"ffc16a" andAlpha:1.0]];
[_comment setBorderInactiveColor:[UIColor LVL_colorWithHexString:@"d0d0d0" andAlpha:1.0]];
[_comment setPlaceholder:@"  Comment"];
[self.pageScroll addSubview:_comment];
yPos += WIDTH*0.1667 + 5;
```
and when I call clear function like:
```javascript
[_nameText setText:@""];
[_title setText:@""];
[_comment setText:@""];
[_nameText becomeFirstResponder];
```
the placeholder do not move down.

Thank & Regard,
-- Luc.

**Comment by LadyRanger1992** [comment] 2015-09-30 04:46
<img width="375" alt="screen shot 2015-09-30 at 11 35 01 am" src="https://cloud.githubusercontent.com/assets/6637801/10184483/552d1efe-6767-11e5-9c98-9785a274e921.png">

**Comment by raulriera** [comment] 2015-09-30 08:03
Hey Luc,

Could you tell me which version are you running? I have never tried them against Objective-C, but they should behave the same

**Comment by LadyRanger1992** [comment] 2015-09-30 08:20
hi Raul,
I tried using your lastest version of your HoshiTextField.
I download it today. It is version 0.4.4.

**Comment by raulriera** [comment] 2015-09-30 08:25
Could you try clearing them with `nil` to test  something? I think my conditional is wrong

**Comment by LadyRanger1992** [comment] 2015-09-30 08:27
I tried with ```nil``` but behavior are the same.
I think you should handle action same with #13.

**Comment by raulriera** [comment] 2015-09-30 08:29
The thing is that I have a property observer on text, so any changes to it should fall into this , this looks correct in a playground... I will try it in the effects directly

![screen shot 2015-09-30 at 09 30 12](https://cloud.githubusercontent.com/assets/24159/10188246/b7984abc-6755-11e5-82ff-d57fa30ceead.png)

**Comment by LadyRanger1992** [comment] 2015-09-30 08:34
I think it not really correct, because ```text = ""``` may be difference with your text.
Because it not same memoris address.
you can check by count text.length = 0 or not.

**Comment by raulriera** [comment] 2015-09-30 08:36
I ran a test on the demo project itself and it seems to work correctly... can you try using `text = @""` instead? Is  either that or a bug between Objective-C and Swift property observers, can't really think of anything else at the moment :/

![gif](https://cloud.githubusercontent.com/assets/24159/10188366/a839952a-6756-11e5-9b7b-36ca8363e590.gif)

**Comment by LadyRanger1992** [comment] 2015-09-30 08:41
I tried to clean my project, rebuild swift file to parse to Objective-C.
But it not work correct.
Can you help me adding more option to check TextField are emty by texttfield.text.length = 0?
I think it will help.

**Comment by raulriera** [comment] 2015-09-30 08:55
When are you calling your clear method? Just tested it in Objective-C and it works as well. BUT, if you call the clear too quickly before the animation is finished, the field won't go down apparently (I can reproduce the bug if I set it on viewDidLoad and clear it on viewDidAppear)

![gif](https://cloud.githubusercontent.com/assets/24159/10188688/59b8bd06-6759-11e5-8ccb-b963a8ea4fec.gif)

**Comment by LadyRanger1992** [comment] 2015-09-30 08:58
I has a button to clear the Text-field, when I inputted value to textfield, I tappd the button to check, if not correct, I clean the textfield

**Comment by raulriera** [comment] 2015-09-30 08:59
Can you try clearing it like I did in that image?

**Comment by LadyRanger1992** [comment] 2015-09-30 08:59
Yes I tried.

**Comment by raulriera** [comment] 2015-09-30 09:00
Don't know what to say then, unable to reproduce it

**Comment by LadyRanger1992** [comment] 2015-09-30 09:05
HI Raul,
I know about your issue.
When I tried to set ```more than 3``` textfield to emty. This bug will be appear.

**Comment by raulriera** [comment] 2015-09-30 09:09
Closing this, if you have a project that can reproduce this error please share it... attaching an example with 3 textfields (which won't matter how many there are)

![gif](https://cloud.githubusercontent.com/assets/24159/10188956/46e4fc4c-675b-11e5-8707-9f4c999bd6c9.gif)

**Closed by raulriera** 2015-09-30 09:09 UTC
Labels: invalid

**Comment by LadyRanger1992** [comment] 2015-09-30 09:27
Hi Raul,
This is my example to reproduce this issue.
https://github.com/LadyRanger1992/HoshiTextField-Issue
Thank for your help.

**Comment by raulriera** [comment] 2015-09-30 09:39
Hey,

Several files are not included in the project and I don't see any code that is actually using the textfield effects.

Lastly, don't include the TextFieldEffects.h into your project

**Comment by LadyRanger1992** [comment] 2015-09-30 09:44
I sorry because I forgot to "Push" with git.
Can you check again?
Thank.

**Comment by raulriera** [comment] 2015-09-30 09:49
If you check your `TextFieldsEffects.swift` you are not using the latest version

**Comment by LadyRanger1992** [comment] 2015-09-30 09:54
I updated lastest version for all file, this resolved.
Thank for your help.

**Comment by dilizarov** [comment] 2015-10-02 14:53
@raulriera I'm running into the issue when clearing too quickly and the field not going down. A fix in the works? Any quick fix you can think of? I can't say I know why it happens, but perhaps it is a clash of the animation going up not letting the animation to go down to fire? Might be able to keep a flag on clear happening too quickly and if it does, call clear after a small delay or something.

**Comment by raulriera** [comment] 2015-10-02 21:12
Hey, can you make a pull request of that fix? 😄 I would love it... thanks

**Comment by raulriera** [comment] 2015-10-02 21:13
Wouldn't BeingFromCurrentState fixed the issue?

**Comment by dilizarov** [comment] 2015-10-02 21:45
@raulriera Not sure I follow. You already use .BeginFromCurrentState and it doesn't work.

I'll make a pull request.
