### ISSUE TITLE
Unknown class YoshikoTextField in Interface Builder file

### ISSUE THREAD

**Issue by mohammad19991** [raulriera/TextFieldEffects#71] opened 2016-04-14 13:43 UTC

**Comment by raulriera** [comment] 2016-04-14 13:49
Can you provide more information to this?

**Comment by mohammad19991** [comment] 2016-04-14 14:11
I just add YoshikoTextField as a subclass for the TextField and it's showing this error

**Comment by mohammad19991** [comment] 2016-04-14 14:18
warning from IB: IB Designables: Using class UITextField for object with custom class because the class YoshikoTextField does not exist

**Comment by raulriera** [comment] 2016-04-14 14:24
How did you install the library? Do you have an example project? I say this because this "obviously works", it's how the example project in this repo is built. I would need more information that just these messages to debug

**Comment by mohammad19991** [comment] 2016-04-15 10:17
I installed the library using cocoapods and created the the textfields in storyborad subclassed from YoshikoTextField. That's it. and the above warning message keeps showing

**Comment by raulriera** [comment] 2016-04-15 10:28
I am going to close this as I can not reproduce this issue without more information. If you can provide an example project where the warning is present please let me know so I can re open this.

Also, make sure you are using the TextFieldEffects module in the "Custom Module" section

**Closed by raulriera** 2016-04-15 10:28 UTC
Labels: invalid

**Comment by mohammad19991** [comment] 2016-04-15 10:36
yea assigning Custom Module to TextFieldEffects solved the problem
Thanks

**Comment by mBabbage** [comment] 2018-11-15 13:00
I know this is closed. I apologise but the custom module on my Identity inspector is empty, though the classes are there. This is causes an "Unknown class error"
**I'm using Carthage**
<img width="717" alt="screenshot 2018-11-15 at 1 57 29 pm" src="https://user-images.githubusercontent.com/7917974/48554416-9f6e7480-e8de-11e8-8cdb-794d41e88203.png">

**Comment by xrisyz** [comment] 2018-11-18 20:42
Cool

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by raulriera** [comment] 2018-11-18 20:49
Are you able to type it into the module box anyway?

**Comment by mBabbage** [comment] 2018-11-19 16:54
Yeah. But I don't have access to the customization on the attributes inspector
