### ISSUE TITLE
YokoTextField does not update when text is set programmatically

### ISSUE THREAD

**Issue by mstorch** [raulriera/TextFieldEffects#32] opened 2015-09-25 19:19 UTC
Hi @raulriera, nice work on these effects, they look and function great!!

Noticed one issue when using YokoTextField.  If you set the text on the field after it is already visible, the field does not animate and still shows as if the text is empty.

To reproduce, simply pre-populate a text field in viewDidAppear(animated) instead of viewWillAppear(animated) and the text field won't show the "populated" appearance until you click on it.  Let me know if you need an example project to show it, happy to help!

Thanks a lot.

**Comment by raulriera** [comment] 2015-09-25 19:55
Hi,

Yeah several appear to be broken when using viewDidAppear, but not with viewDidLoad.... I will try to see where the problem is.

Thanks

**Comment by raulriera** [comment] 2015-09-25 20:03
```swift
override public var text: String? {
        didSet {
            if let _ = text {
                animateViewsForTextEntry()
            } else {
                animateViewsForTextDisplay()
            }
        }
    }
```

You for the moment subclass them and use that, I will test this out further and see if there is a better way

**Comment by mstorch** [comment] 2015-09-25 20:22
I'll try it out. Thanks!

**Comment by raulriera** [comment] 2015-09-27 13:33
Fixed in release 0.4.4

**Closed by raulriera** 2015-09-27 13:33 UTC
Labels: bug
